accounts/urls.py
from django.urls import path
from accounts.views import CustomStaffLoginView, CustomManagementLoginView
from inventory.views import staff_page
app_name = "accounts"

urlpatterns = [
    path("staff-login/", CustomStaffLoginView.as_view(), name="staff-login"),
    path("management-login/", CustomManagementLoginView.as_view(), name="management-login"),
    path('profile/', staff_page, name='profile'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import handler403
from management.views import permission_denied_view

# handler403 = permission_denied_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('inventory.urls')),
    path('management/', include('management.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventory/urls.py
from django.urls import path
from inventory import views

app_name = 'inventory'
urlpatterns = [
    path('', views.index, name='index'),
    path('inventory/', views.staff_page, name='staff-page'),
]

inventory/models.py
from django.db import models
from django_jalali.db import models as jmodels

STATUS = [
    ('I', 'Installation'),
    ('O', 'Opt Out'),
    ('D', 'Defective'),
]

class Device(models.Model):
    objects = jmodels.jManager()
    created_date =  jmodels.jDateTimeField(auto_now_add=True)
    receip_date = jmodels.jDateTimeField(null=True, blank=True)
    staff = models.ForeignKey(to='accounts.Staff', on_delete=models.DO_NOTHING)
    device_code = models.CharField(max_length=255, unique=True)
    status = models.CharField(max_length=1, choices=STATUS)
    recepted = models.BooleanField(null=True)
    installed = models.BooleanField(null=True)

    def __str__(self):
        return self.device_code

inventory/views.py
from django.shortcuts import render, redirect
from inventory.models import Device
from django.db.models import Q
from jdatetime import datetime
from django.contrib import messages

from django.contrib.auth.decorators import login_required, permission_required

def index(request):
    return render(request, 'inventory/index.html')

@login_required
@permission_required('accounts.view_staff_page', raise_exception=True)
def staff_page(request):
    try:
        rows = Device.objects.filter(Q(recepted=None) & Q(installed=None), staff=request.user).order_by('-created_date')
        now = datetime.now()
        context = {'rows':rows, 'now':now}
        if request.method == "POST":
            staff = request.user.staff
            sn = request.POST.get('sn')
            if staff and sn:
                Device.objects.create(staff=staff, device_code=sn, status='O')
                messages.success(request, 'دستگاه نصبی با موفقیت ثبت شد.')
                return render(request, 'inventory/job.html', context)
            else:
                messages.error(request, 'لطفاً تمام فیلدها را پر کنید.')
                return render(request, 'inventory/job.html', context)

        return render(request, 'inventory/job.html', context)
    except PermissionError:
        messages.error(request, "You do not have permission to view this page.")
        return redirect('inventory:index')

inventory/templates/inventory/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static "css/index_style.css" %}">
</head>
<body>
    <div class="container">
        <div class="app-title">
            <h1>.پنل مورد نظر را انتخاب کنید</h1>
        </div>
        <div class="button">
            <div class="admin">
                <a href="{% url "accounts:management-login" %}"><button>پنل سرپرست</button></a>
            </div>
            <div class="staff">
                <a href="{% url "accounts:staff-login" %}"><button>پنل پشتیبان</button></a>
            </div>
        </div>
    </div>
</body>
</html>

inventory/templates/inventory/job.html
{% load static %}
{% load jformat %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>انبار پشتیبان</title>
    <link rel="stylesheet" href="{% static "css/job.css" %}">
    {% comment %} <script src="https://unpkg.com/jalali-moment/dist/jalali-moment.browser.js"></script> {% endcomment %}
</head>
<body dir="rtl">
    <div class="user">
        <div class="user-navbar">
            <div class="title-user">
                <h1 id="user-name">{{ request.user.get_full_name }}</h1>
                <h2 id="date-now">
                    {{ now|jformat:"%H:%M  %Y/%m/%d" }}
                    {% comment %} <script>
                        date =moment();
                        date = date.format("hh/m");
                        document.getElementById('date-now').innerHTML= date
                    </script> {% endcomment %}
                </h2>
            </div>
        </div>
    </div>
    <!-- form -->
    <div class="table">
        <h1>انبار پشتیبان</h1>
        <table class="content-table">
            <thead>
                <tr>
                    <th>وضعیت</th>
                    <th>سریال دستگاه</th>
                    <th>تاریخ رسید</th>
                </tr>
            </thead>
            <tbody>
                {% for row in rows %}
                    <tr>
                        
                        {% if row.status == 'I' %}
                            <td>نصب</td>
                        {% elif  row.status == 'O' %}
                            <td>انصرافی</td>
                        {% elif row.status == 'D' %}
                            <td>معیوب</td>
                        {% endif %}
                        <td>{{ row.device_code }}</td>
                        <td>{{ row.created_date|jformat:"%Y/%m/%d" }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <form class="send" action="{% url "inventory:staff-page" %}" method="POST">
            {% csrf_token %}
            <h1 class="send-h1">عودت دستگاه انصرافی</h1>
            <div class="send-input">
            <label for="sn">سریال دستگاه</label>
                <input type="text" name="sn" id="">
                <button class="btn" type="submit">ثبت</button>
            </div>
        </form>
    </div>

</body>
</html>