core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import handler403
from management.views import permission_denied_view

# handler403 = permission_denied_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('inventory.urls')),
    path('management/', include('management.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventory/urls.py
from django.urls import path
from inventory import views

app_name = 'inventory'
urlpatterns = [
    path('', views.index, name='index'),
    path('inventory/', views.staff_page, name='staff-page'),
]

management/urls.py
from django.urls import path
from management import views
handler403 = views.permission_denied_view
app_name = 'management'


urlpatterns = [
    path('', views.management_select_page, name='management-select-page'),
    path('allocation/', views.allocation_page, name='allocation-page'),
    path('inventory/', views.inventory_page, name='inventory-page'),
    path('inventory/recepted/<str:device_code>/', views.recepted, name="recepted"),
    path('inventory/installed/<str:device_code>/', views.installed, name="installed"),
]

inventory/models.py
from django.db import models
from django_jalali.db import models as jmodels

STATUS = [
    ('I', 'Installation'),
    ('O', 'Opt Out'),
    ('D', 'Defective'),
]

class Device(models.Model):
    objects = jmodels.jManager()
    created_date =  jmodels.jDateTimeField(auto_now_add=True)
    receip_date = jmodels.jDateTimeField(null=True, blank=True)
    staff = models.ForeignKey(to='accounts.Staff', on_delete=models.DO_NOTHING)
    device_code = models.CharField(max_length=255, unique=True)
    status = models.CharField(max_length=1, choices=STATUS)
    recepted = models.BooleanField(null=True)
    installed = models.BooleanField(null=True)

    def __str__(self):
        return self.device_code

management/models.py
from django.db import models

# Create your models here.

management/forms.py
from django import forms

class ReturningDefectiveDeviceFrom(forms.Form):
    pass

inventory/views.py
from django.shortcuts import render, redirect
from inventory.models import Device
from django.db.models import Q
from jdatetime import datetime
from django.contrib import messages

from django.contrib.auth.decorators import login_required, permission_required

def index(request):
    return render(request, 'inventory/index.html')

@login_required
@permission_required('accounts.view_staff_page', raise_exception=True)
def staff_page(request):
    try:
        rows = Device.objects.filter(Q(recepted=None) & Q(installed=None), staff=request.user).order_by('-created_date')
        now = datetime.now()
        context = {'rows':rows, 'now':now}
        if request.method == "POST":
            staff = request.user.staff
            sn = request.POST.get('sn')
            if staff and sn:
                Device.objects.create(staff=staff, device_code=sn, status='O')
                messages.success(request, 'دستگاه نصبی با موفقیت ثبت شد.')
                return render(request, 'inventory/job.html', context)
            else:
                messages.error(request, 'لطفاً تمام فیلدها را پر کنید.')
                return render(request, 'inventory/job.html', context)

        return render(request, 'inventory/job.html', context)
    except PermissionError:
        messages.error(request, "You do not have permission to view this page.")
        return redirect('inventory:index')

management/views.py
from django.shortcuts import render, redirect
from accounts.models import Staff
from django.contrib import messages
from inventory.models import Device
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
from django.core.exceptions import PermissionDenied
from jdatetime import datetime
from django.contrib.auth.decorators import login_required, permission_required

@login_required
@permission_required('accounts.view_admin_page', raise_exception=True)
def management_select_page(request):
    try:
        context = {}
        return render(request, 'management/origin.html', context)
    except PermissionDenied:
        messages.error(request, "You do not have permission to view this page.")
        return redirect('inventory:index')


@login_required
@permission_required('accounts.view_admin_page', raise_exception=True)
def allocation_page(request):
    try:
        all_staffs = Staff.objects.filter(user_type='S')
        all_devices = Device.objects.all().order_by('-created_date')
        now = datetime.now()
        context = {'all_staffs': all_staffs, 'all_devices': all_devices, 'now':now}
        if request.method == "POST":
            staff_id = request.POST.get('staff-name')
            sn = request.POST.get('sn')
            if staff_id and sn:
                try:
                    staff = Staff.objects.get(pk=staff_id)
                    Device.objects.create(staff=staff, device_code=sn, status='D')
                    messages.success(request, 'دستگاه معیوب با موفقیت ثبت شد.')
                    return render(request, 'management/allocation.html', context)
                except Staff.DoesNotExist:
                    messages.error(request, 'پشتیبان مورد نظر یافت نشد.')
            else:
                messages.error(request, 'لطفاً تمام فیلدها را پر کنید.')

        return render(request, 'management/allocation.html', context)
    except PermissionDenied:
        messages.error(request, "You do not have permission to view this page.")
        return redirect('inventory:index')


@login_required
@permission_required('accounts.view_admin_page', raise_exception=True)
def inventory_page(request):
    try:
        all_staffs = Staff.objects.filter(user_type='S')
        now = datetime.now()
        all_devices = Device.objects.all().order_by('-created_date')
        context = {'all_devices': all_devices, 'now':now, 'all_staffs': all_staffs}
        if request.method == "POST":
            staff_id = request.POST.get('staff-name')
            sn = request.POST.get('sn')
            print(staff_id)
            print(sn)
            if staff_id and sn:
                try:
                    staff = Staff.objects.get(id=staff_id)
                    Device.objects.create(staff=staff, device_code=sn, status='I')
                    messages.success(request, 'دستگاه نصبی با موفقیت ثبت شد.')
                    return render(request, 'management/inventory.html', context)
                except Staff.DoesNotExist:
                     messages.error(request, 'پشتیبان مورد نظر یافت نشد.')
            else:
                messages.error(request, 'لطفاً تمام فیلدها را پر کنید.')
        return render(request, 'management/inventory.html', context)
    except PermissionDenied:
        messages.error(request, "You do not have permission to view this page.")
        return redirect('inventory:index')

@login_required
@permission_required('accounts.view_admin_page', raise_exception=True)
def recepted(request, device_code):
    try:
        device = Device.objects.get(device_code=device_code)
        device.recepted = True
        device.receip_date = timezone.now()
        device.save()
    except PermissionDenied:
        messages.error(request, "You do not have permission to view this page.")
        return redirect('inventory:index')    
    except Device.DoesNotExist:
        messages.error(request, 'دستگاه مورد نظر در دسترس نیست.')
    return HttpResponseRedirect(reverse('management:inventory-page'))



@login_required
@permission_required('accounts.view_admin_page', raise_exception=True)
def installed(request, device_code):
    try:
        device = Device.objects.get(device_code=device_code)
        device.installed = True
        device.receip_date = timezone.now()
        device.save()
    except PermissionDenied:
        messages.error(request, "You do not have permission to view this page.")
        return redirect('inventory:index')    
    except Device.DoesNotExist:
        print('device does not exist')
        messages.error(request, 'دستگاه مورد نظر در دسترس نیست.')
        return redirect('inventory:index')
    return HttpResponseRedirect(reverse('management:allocation-page'))


def permission_denied_view(request, exception):
    messages.error(request, "You do not have permission to view this page.")
    return redirect('inventory:index')

management/templates/management/allocation.html
{% load static %}
{% load jformat %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ثبت و تخصیص</title>
    <link rel="stylesheet" href="{% static "css/inventory.css" %}">
    <script src="https://unpkg.com/jalali-moment/dist/jalali-moment.browser.js"></script>
</head>
<body dir="rtl">
    <div class="user">
        <div class="user-navbar">
            <div class="title-user">
                <h1 id="user-name">{{ request.user.get_full_name}}</h1>
                <h2 id="date-now">
                    {{ now|jformat:"%H:%M  %Y/%m/%d" }}
                    {% comment %} <script>
                        date =moment();
                        date = date.format("hh/m");
                        document.getElementById('date-now').innerHTML= date
                    </script> {% endcomment %}
                </h2>
            </div>
        </div>
    </div>
    <!-- form -->
    <div class="table">
        <h1>تابلو ثبت و تخصیص</h1>
        <table class="content-table">
            <thead>
                <tr>
                    <th>وضعیت نصب</th>
                    <th>وضعیت</th>
                    <th>سریال دستگاه</th>
                    <th>نام پشتیبان</th>
                    <th>تاریخ حواله</th>
                    <th>تاریخ رسید</th>
                </tr>
            </thead>
            <tbody>
                {% for device in all_devices %}
                    <tr>
                        <td>
                            {% if device.status == "I" and not device.recepted and not device.installed %}
                                <a href="{% url "management:installed" device_code=device.device_code %}" class="td-button">نصب شد</a>
                            {% elif device.installed %}
                                <p>نصب شد</p>
                            {% elif device.recepted %}
                                <p>رسید شد</p>
                            {% endif %}
                        </td>

                        {% if device.status == 'I' %}
                            <td>نصب</td>
                        {% elif  device.status == 'O' %}
                            <td>انصرافی</td>
                        {% elif device.status == 'D' %}
                            <td>معیوب</td>
                        {% endif %}
                        <td>{{ device.device_code}}</td>
                        <td>{{ device.staff.get_full_name }}</td>
                        <td>{{ device.created_date|date:"Y/m/d"}}</td>
                        <td>{{ device.receip_date|date:"Y/m/d" }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <form class="send" method="POST" action="">
            {% csrf_token %}
            <h1 class="send-h1">عودت دستگاه معیوب</h1>
            <div class="send-input">
                <label for="staff-name">نام پشتیبان</label>
                <select name="staff-name" id="">
                    <option value="" disabled="disabled">یک پشتیبان را انتخاب کنید</option>
                    {% for staff in all_staffs %}
                        <option value="{{ staff.id }}">{{ staff.get_full_name }}</option>
                    {% endfor %}
                </select>
                <label for="sn">سریال دستگاه معیوب</label>
                <input type="text" name="sn" id="">
            <button class="btn" type="submit">ثبت</button>
            </div>
        </form>
    </div>

</body>
</html>

management/templates/management/inventory.html
{% load static %}
{% load jformat %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>انبار</title>
    <link rel="stylesheet" href="{% static "css/inventory.css" %}">
    <script src="https://unpkg.com/jalali-moment/dist/jalali-moment.browser.js"></script>
</head>
<body dir="rtl">
    <div class="user">
        <div class="user-navbar">
            <div class="title-user">
                <h1 id="user-name">{{ request.user.get_full_name}}</h1>
                <h2 id="date-now">
                    {{ now|jformat:"%H:%M  %Y/%m/%d" }}
                    {% comment %} <script>
                    date =moment();
                    date = date.format("hh/m");
                    document.getElementById('date-now').innerHTML= date
                    </script> {% endcomment %}
                </h2>
            </div>
        </div>
    </div>
    <!-- form -->
    <div class="table">
        <h1>تابلو انبار </h1>
        <table class="content-table">
            <thead>
                <tr>
                    <th>رسید</th>
                    <th>وضعیت</th>
                    <th>سریال دستگاه</th>
                    <th>نام پشتیبان</th>
                    <th>تاریخ حواله</th>
                    <th>تاریخ رسید</th>
                </tr>
            </thead>
            <tbody>
                {% for device in all_devices %}
                    <tr>
                        <td>
                            {% if device.status == "D" and not device.installed and not device.recepted %}
                                <a href="{% url "management:recepted" device_code=device.device_code %}" class="td-button">رسید</a>


                            {% elif device.status == "I" and not device.installed and not device.recepted %}
                                <a href="{% url "management:recepted" device_code=device.device_code %}" class="td-button">رسید</a>
                            {% elif device.status == "O" and not device.installed and not device.recepted %}
                                <a href="{% url "management:recepted" device_code=device.device_code %}" class="td-button">رسید</a>
                            {% elif device.installed %}
                                <p>نصب شد</p>
                            {% elif device.recepted %}
                                <p>رسید شد</p>
                            {% endif %}
                        </td>

                        {% if device.status == 'I' %}
                            <td>نصب</td>
                        {% elif  device.status == 'O' %}
                            <td>انصرافی</td>
                        {% elif device.status == 'D' %}
                            <td>معیوب</td>
                        {% endif %}
                        <td>{{device.device_code}}</td>
                        <td>{{ device.staff.get_full_name }}</td>
                        <td>{{ device.created_date|date:"Y/m/d"}}</td>
                        <td>{{ device.receip_date|date:"Y/m/d" }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <form method="POST" class="send" action="">
            {% csrf_token %}
            <h1 class="send-h1">حواله دستگاه</h1>
            <div class="send-input">
            <label for="staff-name">نام پشتیبان</label>
            <select name="staff-name" id="">
                <option value="" disabled="disabled">یک پشتیبان را انتخاب کنید</option>
                {% for staff in all_staffs %}
                    <option value="{{ staff.id }}">{{ staff.get_full_name }}</option>
                {% endfor %}
            </select>
            <label for="sn">سریال دستگاه</label>
            <input type="text" name="sn" id="" />
            <button class="btn" type="submit">ثبت</button>
            </div>
        </form>
    </div>

</body>
</html>

management/templates/management/origin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static "css/index_style.css" %}">
</head>
<body>
    <div class="container">
        <div class="app-title">
            <h1>شرکت کارا الکترونیک آریان کیش کاسپین</h1>
        </div>
        <div class="button">
            <div class="admin">
                <a href="{% url "management:inventory-page" %}"><button>پنل انبار</button></a>
            </div>
            <div class="staff">
                <a href="{% url "management:allocation-page" %}"><button>پنل ثبت و تخصیص</button></a>
            </div>
        </div>
    </div>
</body>
</html>